import { RolUsuario } from "@/Crm/features/users/users-rol";

import { CRM_PERMISSION, type CrmPermission } from "./crm-permissions";

const ADMIN_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.DASHBOARD_VER,

  CRM_PERMISSION.CLIENTES_VER,
  CRM_PERMISSION.CLIENTES_CREAR,
  CRM_PERMISSION.CLIENTES_EDITAR,

  CRM_PERMISSION.INSTALACIONES_VER,
  CRM_PERMISSION.INSTALACIONES_CREAR,
  CRM_PERMISSION.INSTALACIONES_EDITAR,

  CRM_PERMISSION.PPPOE_HOMOLOGACIONES_VER,

  CRM_PERMISSION.TICKETS_VER,
  CRM_PERMISSION.SOPORTE_METAS_VER,
  CRM_PERMISSION.SOPORTE_CATEGORIAS_VER,

  CRM_PERMISSION.DESINSTALACIONES_VER,
  CRM_PERMISSION.DESINSTALACIONES_CREAR,
  CRM_PERMISSION.DESINSTALACIONES_AUTORIZAR,

  CRM_PERMISSION.SERVICIOS_VER,

  CRM_PERMISSION.FACTURACION_ZONA_VER,
  CRM_PERMISSION.SECTORES_VER,

  CRM_PERMISSION.BOT_VER,
  CRM_PERMISSION.WHATSAPP_VER,
  CRM_PERMISSION.WHATSAPP_GALERIA_VER,
  CRM_PERMISSION.WHATSAPP_PLANTILLAS_VER,
  CRM_PERMISSION.WHATSAPP_CAMPANAS_VER,

  CRM_PERMISSION.PLANTILLAS_CONTRATO_VER,

  CRM_PERMISSION.RUTAS_COBRO_VER,
  CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

  CRM_PERMISSION.OPTICO_VER,

  CRM_PERMISSION.CREDITOS_VER,
  CRM_PERMISSION.CREDITOS_CREAR,

  CRM_PERMISSION.REGISTROS_ELIMINADOS_VER,

  CRM_PERMISSION.REPORTES_VER,

  CRM_PERMISSION.EMPRESA_VER,
  CRM_PERMISSION.PERFIL_VER,
];

const OFICINA_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.DASHBOARD_VER,

  CRM_PERMISSION.CLIENTES_VER,
  CRM_PERMISSION.CLIENTES_CREAR,
  CRM_PERMISSION.CLIENTES_EDITAR,

  CRM_PERMISSION.INSTALACIONES_VER,
  CRM_PERMISSION.INSTALACIONES_CREAR,
  CRM_PERMISSION.INSTALACIONES_EDITAR,

  CRM_PERMISSION.PPPOE_HOMOLOGACIONES_VER,

  CRM_PERMISSION.TICKETS_VER,
  CRM_PERMISSION.SOPORTE_METAS_VER,
  CRM_PERMISSION.SOPORTE_CATEGORIAS_VER,

  CRM_PERMISSION.DESINSTALACIONES_VER,
  CRM_PERMISSION.DESINSTALACIONES_CREAR,
  CRM_PERMISSION.DESINSTALACIONES_AUTORIZAR,

  CRM_PERMISSION.SECTORES_VER,

  CRM_PERMISSION.BOT_VER,
  CRM_PERMISSION.WHATSAPP_VER,
  CRM_PERMISSION.WHATSAPP_GALERIA_VER,
  CRM_PERMISSION.WHATSAPP_PLANTILLAS_VER,
  CRM_PERMISSION.WHATSAPP_CAMPANAS_VER,

  CRM_PERMISSION.PLANTILLAS_CONTRATO_VER,

  CRM_PERMISSION.RUTAS_COBRO_VER,
  CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

  CRM_PERMISSION.CREDITOS_VER,
  CRM_PERMISSION.CREDITOS_CREAR,

  CRM_PERMISSION.REGISTROS_ELIMINADOS_VER,

  CRM_PERMISSION.REPORTES_VER,

  CRM_PERMISSION.EMPRESA_VER,
  CRM_PERMISSION.PERFIL_VER,
];

export const ROLE_PERMISSIONS: Record<RolUsuario, readonly CrmPermission[]> = {
  [RolUsuario.SUPER_ADMIN]: Object.values(CRM_PERMISSION),

  [RolUsuario.ADMIN]: ADMIN_PERMISSIONS,

  [RolUsuario.COORDINADOR_OPERACIONES]: ADMIN_PERMISSIONS,

  [RolUsuario.OFICINA]: OFICINA_PERMISSIONS,

  [RolUsuario.TIENDA]: [
    CRM_PERMISSION.DASHBOARD_VER,
    CRM_PERMISSION.CLIENTES_VER,
    CRM_PERMISSION.TICKETS_VER,
    CRM_PERMISSION.WHATSAPP_GALERIA_VER,
    CRM_PERMISSION.PERFIL_VER,
  ],

  [RolUsuario.TECNICO]: [
    CRM_PERMISSION.DASHBOARD_TECNICO_VER,
    CRM_PERMISSION.INSTALACIONES_TECNICO_VER,
    CRM_PERMISSION.TICKETS_VER,
    CRM_PERMISSION.PERFIL_VER,
  ],

  [RolUsuario.COBRADOR]: [
    CRM_PERMISSION.DASHBOARD_VER,

    CRM_PERMISSION.CLIENTES_VER,
    CRM_PERMISSION.CLIENTES_CREAR,

    CRM_PERMISSION.TICKETS_VER,

    CRM_PERMISSION.RUTAS_COBRO_VER,
    CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

    CRM_PERMISSION.CREDITOS_VER,
    CRM_PERMISSION.CREDITOS_CREAR,

    CRM_PERMISSION.PERFIL_VER,
  ],
};
